#!/bin/bash

protected_branches="develop main"
current_branch=$(git symbolic-ref HEAD | sed -e 's,refs/heads/,,')

RED='\033[0;31m'
CYAN='\033[1;36m'
YELLOW='\033[1;33m'
NO_COLOR='\033[0m'

for branch in $protected_branches; do
  if [[ "$current_branch" == "$branch" ]]; then
    printf "${RED}Error${NO_COLOR}: \tYou are not supposed to commit directly to the '${CYAN}$current_branch${NO_COLOR}' branch. \n\
      \tOverridable by adding the ${YELLOW}--no-verify${NO_COLOR} flag\n"
    exit 1
  fi
done
